import CopyEndpoint from '../components/common/CopyEndpoint'
import LandingFooter from '../components/layout/LandingFooter'
import LandingHeader from '../components/layout/LandingHeader'
import ModelCatalog from '../features/catalog/ModelCatalog'

const endpoints = [
  ['Chat Completions', '/chat/completions'],
  ['Responses', '/responses'],
  ['Messages', '/messages'],
]

const rates = [
  ['Input tokens', 'The prompt and context you send to the model.'],
  ['Cached input', 'Reused input, at the model’s cached rate when supported.'],
  ['Output tokens', 'The response generated by the model.'],
]

function SectionHeading({ title, children }) {
  return <div className="section-heading"><h2>{title}</h2><p>{children}</p></div>
}

function HomePage() {
  return (
    <div id="top" className="landing-page">
      <a className="skip-link" href="#main-content">Skip to main content</a>
      <LandingHeader />
      <main id="main-content">
        <section className="hero container" aria-labelledby="landing-title">
          <p className="eyebrow">THE MODEL MARKETPLACE FOR DEVELOPERS</p>
          <h1 id="landing-title">Multiple models.<br /><span>One endpoint.</span></h1>
          <p className="hero-description">Compare model prices, connect with one API, and pay for the tokens you use.</p>
          <div className="actions"><a className="button-primary" href="/console">Start building <span>→</span></a><a className="text-link" href="/console/providers?onboarding=new">Sell model access ↗</a></div>
        </section>
        <CopyEndpoint />
        <section className="section container" id="models" aria-labelledby="catalog-title">
          <SectionHeading title="Find the right model.">Published models and their current token prices. Compare the cost before you connect.</SectionHeading>
          <ModelCatalog />
          <div className="catalog-footer"><span>Prices per 1 million tokens</span><a className="text-link" href="/console/models">View all models →</a></div>
        </section>
        <section className="integration section container" id="gateway" aria-labelledby="gateway-title">
          <div><h2 id="gateway-title">Keep your SDK.<br />Change your base URL.</h2><p>Use your existing OpenAI client. Add your LLMHub key, choose a published model, and send your first request.</p><a className="text-link" href="/console/docs">Read the integration guide →</a>
            <dl className="protocols">{endpoints.map(([name, path]) => <div key={name}><dt>{name}</dt><dd><code>{path}</code></dd></div>)}</dl>
          </div>
          <div className="code-card"><div><span>Your first request</span><span>Python</span></div><pre tabIndex="0"><code>{`from openai import OpenAI

client = OpenAI(
    base_url="/v1",
    api_key="YOUR_LLMHUB_KEY",
)

response = client.chat.completions.create(
    model="YOUR_MODEL_ID",
    messages=[{"role": "user", "content": "Hello"}],
)`}</code></pre></div>
        </section>
        <section className="section container" id="rates" aria-labelledby="pricing-title">
          <SectionHeading title="Know what each request costs.">Input, cached input, and output have separate rates. Review usage and charges in your console.</SectionHeading>
          <dl className="rate-details">{rates.map(([term, description]) => <div key={term}><dt>{term}</dt><dd>{description}</dd></div>)}</dl>
          <a className="text-link" href="/console/billing">Explore billing →</a>
        </section>
      </main>
      <LandingFooter />
    </div>
  )
}

export default HomePage
